In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [2]:
import numpy as np

In [3]:
for i in range(1, 11) :
    print(i ,end=' ')

1 2 3 4 5 6 7 8 9 10 

In [11]:
#arrays
arr = np.array({1,2,3,4,5,6,6})
arr

array({1, 2, 3, 4, 5, 6}, dtype=object)

In [5]:
arr = np.array([1, 2.34, 10, 20, 4.5])    #numpy is homogeneous so it has same data type values
arr

array([ 1.  ,  2.34, 10.  , 20.  ,  4.5 ])

In [8]:
arr = np.array([1,2,3,4,5, 'hello' , 4.5])
arr

array(['1', '2', '3', '4', '5', 'hello', '4.5'], dtype='<U32')

In [7]:
type(arr)

numpy.ndarray

In [13]:
arr.dtype

dtype('O')

In [15]:
arr = np.array([1,2,3,4.5,'hello'])
arr.dtype

dtype('<U32')

In [16]:
[type(i) for i in arr]

[numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_]

In [17]:
arr = np.array([1,2.34,32432,23432,234.23432] , dtype = 'str')


In [18]:
arr


array(['1', '2.34', '32432', '23432', '234.23432'], dtype='<U9')

In [19]:
arr = np.array([i for i in range(1, 100)])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
arr = np.array(range(1, 10))
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
newarr = np.array([[1,2,3,4] , [10,20,30, None]])

In [24]:
newarr.ndim

2

In [25]:
newarr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])      #3d arrays coz nested 2d arrays   #shape = (2,2,2)
newarr.ndim

3

In [26]:
newarr = np.array([[1,2,3,4] , [10,20,30, None]])
newarr.shape

(2, 4)

In [27]:
newarr

array([[1, 2, 3, 4],
       [10, 20, 30, None]], dtype=object)

In [28]:
len(newarr)

2

In [29]:
newarr.size     #count the no of elements

8

In [30]:
newarr


array([[1, 2, 3, 4],
       [10, 20, 30, None]], dtype=object)

In [31]:
newarr = newarr.reshape(1,8)

In [32]:
newarr



array([[1, 2, 3, 4, 10, 20, 30, None]], dtype=object)

In [33]:
arr = np.array([2,23,23,2,32,32,3,232])
arr

array([  2,  23,  23,   2,  32,  32,   3, 232])

In [34]:
newarr.ndim

2

In [35]:
newarr

array([[1, 2, 3, 4, 10, 20, 30, None]], dtype=object)

In [36]:
newarr.ndim      #due to two square brackets just adjusted so 2

2

In [37]:
arr

array([  2,  23,  23,   2,  32,  32,   3, 232])

In [38]:
arr.ndim

1

In [39]:
newarr

array([[1, 2, 3, 4, 10, 20, 30, None]], dtype=object)

In [40]:
newarr = np.array([[1,2,3,4] , [10,20,30, None]])
newarr

array([[1, 2, 3, 4],
       [10, 20, 30, None]], dtype=object)

In [41]:
newarr.reshape(-1)      #in this those two brackets gone

array([1, 2, 3, 4, 10, 20, 30, None], dtype=object)

In [42]:
newarr

array([[1, 2, 3, 4],
       [10, 20, 30, None]], dtype=object)

In [46]:
newarr.flatten()


array([1, 2, 3, 4, 10, 20, 30, None], dtype=object)

In [44]:
newarr

array([[1, 2, 3, 4],
       [10, 20, 30, None]], dtype=object)

In [47]:
newarr.shape

(2, 4)

In [48]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.zeros([2,5] , dtype = 'int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
np.ones(10, dtype = 'str')

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [51]:
np.ones([2,5] , dtype = 'str')

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [52]:
np.identity(4 , dtype = 'int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [58]:
np.identity(3 , dtype = 'str')

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

In [54]:
np.identity(3 , dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [59]:
np.eye(5, dtype = 'int')      #default dtype is float  

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [62]:
np.eye(3, 4, k=1 , dtype='int')

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [65]:
np.full(10,5).reshape(2,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [66]:
np.full([2,5] , 5 , dtype='int')

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [67]:
np.full([2,5] , 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [68]:
list(range(1 ,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [69]:
np.arange(1.5 , 10.6)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [70]:
np.arange(1 , 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [71]:
np.linspace(1 , 100 , 4 , retstep= True)

(array([  1.,  34.,  67., 100.]), 33.0)

In [72]:
arr = np.arange(1,11).reshape(2,5)

In [73]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [75]:
arr*10

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [76]:
arr>6

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [77]:
arr[arr>6]

array([ 7,  8,  9, 10])

In [78]:
#indexing and slicing
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [79]:
arr[0][4]

5

In [80]:
arr[0][4] = 23.345

In [81]:
arr

array([[ 1,  2,  3,  4, 23],
       [ 6,  7,  8,  9, 10]])

In [82]:
arr

array([[ 1,  2,  3,  4, 23],
       [ 6,  7,  8,  9, 10]])

In [83]:
arr[1][1:]

array([ 7,  8,  9, 10])

In [84]:
arr[1 , 1:]

array([ 7,  8,  9, 10])

In [85]:
arr

array([[ 1,  2,  3,  4, 23],
       [ 6,  7,  8,  9, 10]])

In [86]:
arr[: , 2:]

array([[ 3,  4, 23],
       [ 8,  9, 10]])

In [87]:
#random values
np.random.randint(1,10)

3

In [88]:
np.random.randint(1,10,3)

array([1, 4, 4])

In [89]:
np.random.randint(1,11 , [2,5])

array([[5, 7, 6, 9, 6],
       [8, 3, 5, 3, 6]])

In [90]:
np.random.rand(4)

array([0.29502059, 0.19505364, 0.69679961, 0.54746976])

In [91]:
np.random.rand(2,3)

array([[0.20162659, 0.68848627, 0.13631169],
       [0.57791945, 0.4763716 , 0.45188843]])

In [92]:
np.random.randn(5)

array([-1.33528453,  1.13106252, -0.12659008,  0.79590658, -0.49459323])

In [93]:
np.random.randn(2,3)

array([[ 0.83970364,  0.86424643, -0.74526071],
       [-0.43942567, -0.40948073, -0.84519967]])

In [94]:
np.__version__

'1.26.4'

In [95]:
arr = np.arange(1,10)
np.quantile(arr , 0.25)

3.0

In [96]:
np.quantile(arr, 0.5)

5.0

In [97]:
#view and copy
arr = np.array([[1,2,3] , [10,20,30]])
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [98]:
newarr = arr.view()

In [99]:
newarr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [3]:
import numpy as np                              #import next day again
arr = np.array([[1,2,3] , [10,20,30]])
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [4]:
newarr = arr.view()
newarr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [5]:
arr[0][1] = 100
arr

array([[  1, 100,   3],
       [ 10,  20,  30]])

In [6]:
newarr

array([[  1, 100,   3],
       [ 10,  20,  30]])

In [7]:
neww = arr.copy()

In [8]:
arr

array([[  1, 100,   3],
       [ 10,  20,  30]])

In [9]:
neww

array([[  1, 100,   3],
       [ 10,  20,  30]])

In [10]:
arr[0][-1] = -1
arr

array([[  1, 100,  -1],
       [ 10,  20,  30]])

In [11]:
neww

array([[  1, 100,   3],
       [ 10,  20,  30]])

In [12]:
#stats
arr

array([[  1, 100,  -1],
       [ 10,  20,  30]])

In [13]:
np.mean(arr)

26.666666666666668

In [14]:
np.median(arr)

15.0

In [15]:
np.min(arr)

-1

In [16]:
np.max(arr)

100

In [17]:
np.sin(arr)

array([[ 0.84147098, -0.50636564, -0.84147098],
       [-0.54402111,  0.91294525, -0.98803162]])

In [18]:
np.cos(arr)

array([[ 0.54030231,  0.86231887,  0.54030231],
       [-0.83907153,  0.40808206,  0.15425145]])

In [19]:
np.tan(arr)

array([[ 1.55740772, -0.58721392, -1.55740772],
       [ 0.64836083,  2.23716094, -6.4053312 ]])

In [20]:
arr.T

array([[  1,  10],
       [100,  20],
       [ -1,  30]])

In [22]:
newarr = np.arange(1,11).reshape(2,5)

In [23]:
newarr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
m = int(input('Enter a number:'))
n = int(input('Enter a number:'))
arr = np.random.randint(1,100, [m,n])
arr

Enter a number: 3
Enter a number: 4


array([[82, 72, 93, 58],
       [53, 85, 15, 23],
       [ 8, 59, 16,  3]])